### ISSUE TITLE
Feature request: MOD+scroll to zoom

### ISSUE THREAD

**Issue by suve** [wjaguar/mtPaint#41]
It would be a nice feature to be able to control the zoom level using the mousewheel. Many other programs allow to do this via CTRL+scrool. mtPaint uses CTRL to scroll horizontally, so maybe SHIFT could be used?

**Comment by wjaguar** [comment]
Preferences->Interface->Mouse Scroll Wheel = Zoom , since times immemorial.

Myself I never saw the point of doing that in mtPaint however, for unlike those "many other programs" mtPaint has number keys, the 1..9 and 0, bound to zoom levels. Pressing "6" for 800% zoom, "4" to return to 100%, "2" for 25%, etc. is easy and leaves the *scroll* wheel do what it's named for.
