### ISSUE TITLE
Wrong year in About window

### ISSUE THREAD

**Issue by basxto** [wjaguar/mtPaint#49]
It says
> mtPaint 3.50 - Copyright (C) 2004-2016 The Authors

This might be a problem of translations

**Comment by wjaguar** [comment]
And what should I answer to that, except "It doesn't, since version 3.50" ?

Yes it sat at 2016 until the actual 3.50 commit; it would be pretty pathetic, after missing that date, to set a new one only to possibly miss it again, wouldn't it?
And now, since the very next version 3.50.01, it is at 3.51 and 2021. Which the makehelp script took verbatim from README, which is displayed in its full ASCII glory on the project's Github page.

As to translations, I use a Perl script to fix the whole bunch of them prior to a release; things like version numbers and years are written the same in any language, thus do not need any customization.
