### ISSUE TITLE
Pipette stops working after a while

### ISSUE THREAD

**Issue by BrauerSuzuki** [wjaguar/mtPaint#71]
I'm trying to retouch a few pixels from a photo. At first the pipette tools works as expected, but after about five applications of the pipette, it doesn't give me the right color anymore. Instead it assigns a much darker color, seemingly random, to the palette. This only happens to a particular type of jpgs, which I got from a photographer.

**Comment by wjaguar** [comment]
Cannot reproduce anything of the sort, here. Even when holding Ctrl and the left button and dragging the cursor across a JPG image, the color A faithfully follows the color under the cursor, that is easily hundreds of "applications of the palette".
If you were using the actual pipette from within a color editor dialog instead of simply a Ctrl+left click (Ctrl+right click for color B), you were doing it wrong, but anyway, that tool also does not develop any faults after five, or ten, uses, here on my system.

If this is happening only for a particular photo, then maybe it is camera matrix's jitter you are seeing. With low enough compression level and unfortunate enough camera make, the actual pixels comprising what your eye sees on a screen as a flat color on a photo, will be in fact a mix of lighter and darker ones, which any of color pickers will be sampling as luck will have it.
To see whether that is what is really happening, increase the zoom to 800%, to get a pixel grid (the shortcut key is "6" for that), and look at the problem area at that zoom. Then try picking a color from within a specific pixel grid cell and see if the result matches what it should be.
In case said kind of pixel jitter is indeed the cause of your problem with the photo, mtPaint has builtin means to combat that kind of problems. You can set brush size to say 2 or 3, and then Ctrl+double click to set the color A to a gamma-corrected _average_ of all the pixels under the brush square.

And in case something else is happening instead, then I'll need a procedure to reproduce the problem, to have any chance to diagnose it.

**Comment by wjaguar** [comment]
In a JPEG there can be present a thing called "color profile" (not proprietary, an ICC standard), and in some photo images it does make a notable difference.
To use it, the "Apply colour profile" checkbox in the load image dialog need be checked (by default it isn't, for historical reasons; maybe I should change the default to ON in the next versions, to prevent problems such as yours). This is a one-time action; mtPaint applies the profile-specified change when loading, and then any image it saves will have regular colors and no profile.

If your version of mtPaint lacks said checkbox, it is either older than dirt, or a bad third-party build with color management disabled, and in either case needs be replaced.

**Comment by BrauerSuzuki** [comment]
Awesome! This did the trick. Since I have opened the file previously from the file manager, I never saw this option. Perhaps, it would be good to have a little dialog before opening a file with a color profile.
