### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by quite** [wjaguar/mtPaint#8]
Any new release planned? Or will it be 3.50? :) Would be great to benefit from the last few years bugfixes through Arch's community packages...

**Comment by RyanBram** [comment]
Hi.
I am also really excited about next release. Hopefully it will get released soon in this 2015.

Thanks for your hard work

**Comment by basxto** [comment]
Latest release is still 3.40 from 2011-12-30

**Comment by axredneck** [comment]
Current git master is much more usable and even more stable than 3.40 for me.

**Comment by wjaguar** [comment]
As it should be, being at the pre-release stage.
The release-blocking issues are not anything with the code, but documenting the new stuff and reviewing/fixing translations.

**Comment by xyproto** [comment]
Please also consider creating a git tag per release, since it would make packaging easier! (I'm maintaining the Arch Linux `mtpaint` package).

**Comment by wjaguar** [comment]
The release version 3.50 finally arrived. :)

**Comment by xyproto** [comment]
Thanks for developing and maintaining `mtpaint`. It's pretty sweet! But could you please create a git tag per release?

**Comment by wjaguar** [comment]
An actual release was the version 3.50 and will be the version 3.51
Everything with 3-part version number is just an interim version.
What would be the actual point of "tagging" every commit with the header of said commit?

I understand the necessity of tags in repositories where random people commit every random modification and not look whether the result compiles. But the development methodology I follow implies going from a working version to a working version, so any single thing that appears here is fit for use, or at the very least intended for field testing (these latter carry a warning). What, exactly, would change with presence of tags on them?

**Comment by axredneck** [comment]
Usually 3.50.1, 3.50.2 etc mean bug fixes. Maybe better call them 3.50beta1, 3.50beta2 etc ?

**Comment by wjaguar** [comment]
Since version 2.00 the numbering here worked like this:
2.00, 3.00 - major additions to functionality: layers, channels
3.10, 3.20, .. 3.50 - a feature release
3.01, 3.02, .. 3.51 - an update release: translations, bugfixes, improvements (aka "let's not break the translations")
3.14, 3.44 .. 3.49 - reserved for the development branch

I.e. the interim versions following a released one, like 3.50.05, are steps to an update release. 3.54.01 will start the new cycle intended to end up with 3.60. If something momentous gets added, numbers will jump to 3.94.01.
